name       : vorbis-tools
version    : 1.4.2
release    : 8
source     :
    - https://downloads.xiph.org/releases/vorbis/vorbis-tools-1.4.2.tar.gz : db7774ec2bf2c939b139452183669be84fda5774d6400fc57fde37f77624f0b0
homepage   : https://xiph.org/vorbis/
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Standard software that allows you to play and encode Ogg Vorbis files
description: |
    This package contains some tools for Ogg Vorbis; ogg123 to play Ogg and FLAC files, oggdec a simple decoder for Ogg Vorbis file to PCM audio file (Wave or RAW), oggenc to encode audio into the Ogg Vorbis format, ogginfo to give information about Ogg files and does extensive validity checking, vcut which allows you to cut up Vorbis files and vorbiscomment to list or edit comments in Ogg Vorbis files.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(flac)
    - pkgconfig(speex)
    - pkgconfig(vorbis)
    - supertux
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
profile    : |
    cp /usr/share/supertux2/sounds/*.wav .
    ./oggenc/oggenc -q 10 *.wav
    ./oggdec/oggdec *.ogg
