name       : vorbis-tools
version    : 1.4.0
release    : 1
source     :
    - http://downloads.xiph.org/releases/vorbis/vorbis-tools-1.4.0.tar.gz : a389395baa43f8e5a796c99daf62397e435a7e73531c9f44d9084055a05d22bc
license    : GPL-2.0
component  : multimedia.audio
summary    : Standard software that allows you to play and encode Ogg Vorbis files
description: |
    Standard software that allows you to play and encode Ogg Vorbis files
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(flac)
    - pkgconfig(ogg)
    - pkgconfig(speex)
    - pkgconfig(vorbis)
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2014-9638.patch
    %patch -p1 < $pkgfiles/security/CVE-2014-9640.patch
    %patch -p1 < $pkgfiles/security/CVE-2015-6749.patch
    %configure
build      : |
    %make
install    : |
    %make_install
