name       : vorbis-tools
version    : 1.4.0
release    : 5
source     :
    - http://downloads.xiph.org/releases/vorbis/vorbis-tools-1.4.0.tar.gz : a389395baa43f8e5a796c99daf62397e435a7e73531c9f44d9084055a05d22bc
license    : GPL-2.0
component  : multimedia.audio
summary    : Standard software that allows you to play and encode Ogg Vorbis files
description: |
    Standard software that allows you to play and encode Ogg Vorbis files
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(flac)
    - pkgconfig(ogg)
    - pkgconfig(speex)
    - pkgconfig(vorbis)
    - supertux
setup      : |
    %apply_patches
    %configure
build      : |
    %make
install    : |
    %make_install
profile    : |
    cp /usr/share/supertux2/sounds/*.wav .
    ./oggenc/oggenc -q 10 *.wav
    ./oggdec/oggdec *.ogg
